### ISSUE TITLE
[SECURITY] Potential security vulnerability in dependencies

### ISSUE THREAD

**Issue by vivi90** [atom-extensions/atom-music#25]
GitHub found potential security vulnerability in dependencies:
https://github.com/atom-extensions/atom-music/network/alerts

**Comment by UziTech** [comment]
`atom-space-pen-views` has not been maintained in a while. We should switch to [`etch`](https://github.com/atom/etch) or [`emel`](https://github.com/UziTech/emel)

**Comment by vivi90** [comment]
@UziTech emel seems to be very efficient but etch looks very similar to JSX and ReactJS for me so i think we should switch over to etch because there is a huge community of JSX and ReactJS that are able to help out later with maintenance.

**Comment by UziTech** [comment]
I agree. Most of my atom packages use etch. emel is very useful for creating elements on the client side when you don't have the luxury of a build step. jsx is much easier to read than emmet.

**Comment by vivi90** [comment]
@UziTech So how to start? Do you want to do this rewrite, because you are already familiar with etch?

**Comment by UziTech** [comment]
Ya I'll work on it this weekend

**Comment by vivi90** [comment]
@UziTech Great! :slightly_smiling_face:

**Comment by vivi90** [comment]
Possible solution: https://github.com/atom-extensions/atom-music/pull/30
