### ISSUE TITLE
[BUG] Doesn't support F32L WAV codec

### ISSUE THREAD

**Issue by vivi90** [atom-extensions/atom-music#31]
Music encoded in F32L WAV (32 Bits float LE) is not supported.
Example: https://soundcloud.com/adyoro-official/hatsune-miku-cat-food-adyoro-remix

**Comment by vivi90** [comment]
@UziTech @sdinesh86 @gyf1214 Do you have any ideas? :-)

**Comment by UziTech** [comment]
since this package uses the [`audio`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio) html tag I don't think there is any way to support codecs that are not supported by the chromium version that Atom bundles.

**Comment by vivi90** [comment]
@UziTech Yes, exactly. But should we provide a fallback solution?

**Comment by UziTech** [comment]
After a quick search it doesn't look like it is possible without the user needing other software installed on their computer.

The only thing I found is [`cody-music`](https://www.npmjs.com/package/cody-music) to play music on itunes or spotify, which is used by [`music-time`](https://atom.io/packages/music-time).

**Comment by vivi90** [comment]
@UziTech Hm great solution for another issue: https://github.com/atom-extensions/atom-music/issues/10#issuecomment-641823816
Okay so i think we need to close this ticket.

If someone is able to found a solution later, please tell us. :slightly_smiling_face:
