### ISSUE TITLE
[FEATURE REQUEST] Option to Upload A Folder

### ISSUE THREAD

**Issue by EpicCodeWizard** [atom-extensions/atom-music#51]
Can this extension have the option to upload an entire folder and a second option to upload an entire folder **A͟N͟D** its subdirectories? Even though you can already do this via:
1. Click ![image](https://user-images.githubusercontent.com/83260377/127406157-aff99a31-f5dd-4aec-bafd-c9991d456663.png).
2. Do ctrl+a while in the file dialog.
3. Click open and all the files are imported.

A more direct option would be helpful. Please consider it!

**Comment by UziTech** [comment]
I think this is a duplicate of #10

**Comment by EpicCodeWizard** [comment]
k thx man

**Comment by EpicCodeWizard** [comment]
Thanks!
