### ISSUE TITLE
Search / navigate in playlist

### ISSUE THREAD

**Issue by Enelar** [atom-extensions/atom-music#7]
Is it possible to popup playlist?

**Comment by sdinesh86** [comment]
I will try to see if i can do anything on it

**Comment by UziTech** [comment]
I think this was fixed in #14 with adding it to the dock

**Comment by vivi90** [comment]
@Enelar Still added with "Search playlist" button and playlist panel by commit https://github.com/sdinesh86/atom-music/pull/14
